spring:
  application:
    name: example-gateway-zuul-reg-exp
server:
  port: 8779
eureka:
  client:
    serviceUrl:
      defaultZone: http://querenjie:123456@localhost:8761/eureka/
    healthcheck:
      enabled: true
    #eureka client刷新本地缓存时间
    #默认30s
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
